- Source/CH03Project/Private/BaseActor.cpp
- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/DamageComponent.cpp
- Source/CH03Project/Public/BaseActor.h
- Source/CH03Project/Public/BaseStatComponent.h
- Source/CH03Project/Public/DamageComponent.h
전투관련 컴포넌트 추가
BaseStatComponent
-체력, 방어력, 무적 처리
-OnDeath() 가상함수로 추가
DamageComponent
-공격력에 따른 타겟의 BaseStatComponent의 체력 감소처리
전투관련 컴포넌트가 포함된 BaseActor 추가
> [기능] 전투관련 컴포넌트가 포함된 BaseActor 추가

- .vsconfig
- CH03Project.uproject
- Config/DefaultEngine.ini
- Content/MainMenuMap.umap
- Content/Map/GameMap.umap
- Content/UITexture/ARImage.uasset
- Content/UITexture/BossHpbar.uasset
- Content/UITexture/Outline.uasset
- Content/UITexture/QuestOutline-Photoroom.uasset
- Content/UITexture/QuickSlot.uasset
- Content/UITexture/RedHpbar.uasset
- Content/UITexture/T_CH001.uasset
- Content/UITexture/T_HM_002.uasset
- Content/UITexture/T_KI_002.uasset
- Content/Widget/MainMenu.uasset
- Content/Widget/WBP_HUDWidget.uasset
- Content/Widget/WBP_MainMenu.uasset
- Content/Widget/WBP_PauseMenu.uasset
- Content/font/Orbitron-Regular.uasset
- Content/font/Orbitron-Regular_Font.uasset
- Content/font/Orbitron-VariableFont_wght.uasset
- Content/font/Orbitron-VariableFont_wght_Font.uasset
- Source/CH03Project/CH03Project.Build.cs
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MenuWidget.cpp
- Source/CH03Project/Public/HUDWidget.h
- Source/CH03Project/Public/MenuWidget.h
UI와 HUD클래스.
관련 함수와 변수 포함
그리고 레벨 블루프린트에서 UI와 HUD를 띄우는 구성까지 추가
> [UI] UI, HUD클래스 변수 및 함수

- Content/MainMenuMap.umap
- Content/Map/GameMap.umap
- Content/Widget/WBP_HUDWidget.uasset
- Content/Widget/WBP_MainMenu.uasset
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MenuWidget.cpp
- Source/CH03Project/Public/HUDWidget.h
- Source/CH03Project/Public/MenuWidget.h
> [UI] 점수 관련 함수

- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/GameModePlay.cpp
- Source/CH03Project/Private/GameStatePlay.cpp
- Source/CH03Project/Private/QuestTypeA.cpp
- Source/CH03Project/Public/BaseStatComponent.h
- Source/CH03Project/Public/GameModePlay.h
- Source/CH03Project/Public/GameStatePlay.h
Hp관련 델리게이트를 BaseStatComponent에 추가 했습니다. 
해당 델리게이트는 GameModePlay에서 받아서 GameStatePlay에 반영됩니다.
이 외에 텍스트, 스코어, 아이템수량 등 연관된 기능들이 추가되면, GameStatePlay와 UI에 반영할 수 있게 수정하겠습니다.
> [리펙토링] Hp 델리게이트 추가

- Content/Widget/WBP_HUDWidget.uasset
- Source/CH03Project/Private/DamageWidget.cpp
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MenuWidget.cpp
- Source/CH03Project/Public/DamageWidget.h
- Source/CH03Project/Public/HUDWidget.h
1. 히트마커를 띄우고 0.3초뒤 사라지는 함수 추가
2. 히트마커 비저빌리티 히든으로 바꾸는 함수 추가
3. HUD상에 데미지 텍스트를 띄우는 함수추가
4. 데미지위젯클래스 추가
5. 데미지위젯클래스에 텍스트 바인드
> [UI,HUD] 히트마커, 데미지텍스트추가

- Content/Character/ABP_Character.uasset
- Content/Levels/MainMenuLevel.umap
- ABP_Character.uasset
- MainmenuLevel.umap
> [백업] 기존 ABP와 메인메뉴레벨 백업

- Content/Blueprints/BP_MyPlayerController.uasset
- Content/Levels/MainLevel.umap
- Content/Levels/MainMenuLevel.umap
- Content/Widget/WBP_MainMenu.uasset
- Source/CH03Project/Private/GameModePlay.cpp
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MenuWidget.cpp
- Source/CH03Project/Private/MyPlayerController.cpp
- Source/CH03Project/Public/GameModePlay.h
- Source/CH03Project/Public/HUDWidget.h
- Source/CH03Project/Public/MenuWidget.h
- Source/CH03Project/Public/MyPlayerController.h
> [UI] UI띄우는 로직추가

- Content/Character/BP_MyCharacter.uasset
- Content/UITexture/HpHealthBar__1_.uasset
- Content/UITexture/RedHpbar.uasset
- Content/Widget/WBP_HUDWidget.uasset
- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/DamageComponent.cpp
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MyPlayerController.cpp
- Source/CH03Project/Public/BaseStatComponent.h
- Source/CH03Project/Public/DamageComponent.h
- Source/CH03Project/Public/MyPlayerController.h
> [UI] 체력관련 함수, 체력바그림 수정

- Content/Character/BP_MyCharacter.uasset
- Content/UITexture/HpHealthBar__1_.uasset
- Content/UITexture/RedHpbar.uasset
- Content/Widget/WBP_HUDWidget.uasset
- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/DamageComponent.cpp
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MyPlayerController.cpp
- Source/CH03Project/Public/BaseStatComponent.h
- Source/CH03Project/Public/DamageComponent.h
- Source/CH03Project/Public/MyPlayerController.h
Reverts NbcampUnreal/3rd_4th-Team11-CH3-Project#37
> Revert "[UI] 체력관련 함수, 체력바그림 수정"

- Content/UITexture/HpHealthBar.uasset
- Content/UITexture/RedHpbar.uasset
- Content/Widget/WBP_HUDWidget.uasset
- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MyPlayerController.cpp
- Source/CH03Project/Public/BaseStatComponent.h
- Source/CH03Project/Public/DamageComponent.h
- Source/CH03Project/Public/MyPlayerController.h
> [UI] 체력바 이미지 변경, 바인드

- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/GameModePlay.cpp
- Source/CH03Project/Private/GameStatePlay.cpp
- Source/CH03Project/Private/MyPlayerController.cpp
- Source/CH03Project/Public/GameStatePlay.h
한순간에 연속으로 대미지가 들어오는 버그 수정
델리게이트 사용하여 스테이지에서 점수관련 함수 사용시 HUDWidget의 UI에 반영
> [리펙토링] 다단히트 버그 수정 및 스테이지 점수 UI에 반영

- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Public/MenuWidget.h
- Source/CH03Project/Public/MyPlayerController.h
> [UI] 게임오버 메뉴 띄우기

- Content/Character/BP_MyCharacter.uasset
- Source/CH03Project/Private/MyCharacter.cpp
- Source/CH03Project/Public/MyCharacter.h
캐릭터
- 부모 변경 ABaseActor->ACharacter
- 스탯컴포넌트, 데미지컴포넌트 헤더 직접 포함 BP_캐릭터
- 에디터에서 만든 컴포넌트 삭제
- 코드에서 추가
- 스탯컴포넌트, 데미지컴포넌트 변수값 설정
> [수정] 캐릭터, BP캐릭터

- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/GameModePlay.cpp
- Source/CH03Project/Private/GameStatePlay.cpp
- Source/CH03Project/Private/QuestTypeA.cpp
- Source/CH03Project/Private/SubTextDataRow.cpp
- Source/CH03Project/Public/GameModePlay.h
- Source/CH03Project/Public/GameStatePlay.h
- Source/CH03Project/Public/QuestTypeA.h
- Source/CH03Project/Public/SubTextDataRow.h
퀘스트 방식을 전면 수정하였고, 게임스테이트에 필요한 델리게이트를 추가하였습니다.
> [리펙토링] 퀘스트 전면 수정

- Content/Blueprints/BP_QuestTypeA.uasset
- Content/DataTables/SubTextTable.uasset
- Source/CH03Project/Private/GameModePlay.cpp
- Source/CH03Project/Private/GameStatePlay.cpp
- Source/CH03Project/Private/MyPlayerController.cpp
- Source/CH03Project/Private/QuestTypeA.cpp
- Source/CH03Project/Public/GameModePlay.h
- Source/CH03Project/Public/QuestTypeA.h
서브미션 텍스트를 변경하였고, 컨트롤러 비긴플레이에 주석처리 해두었습니다.
퀘스트 액터를 블루프린트로 만들어서 세부사항 조정했습니다.
> [리펙토링] 서브미션 텍스트 전달 수정 및 퀘스트 액터 구현

- Content/AI/Characters/AIC_Enemy_Boss.uasset
- Content/AI/Characters/BP_AI_Boss.uasset
- Content/AI/Characters/BP_AI_Melee.uasset
- Content/AI/Characters/BP_AI_Ranged.uasset
- Content/AI/Characters/BT/BB_Enemy.uasset
- Content/AI/Characters/BT/Boss/BB_Boss.uasset
- Content/AI/Characters/BT/Boss/BTS_CombatContext.uasset
- Content/AI/Characters/BT/Boss/BT_Enemy_Boss.uasset
- Content/AI/Characters/BT/Boss/BT_SubTree_PrimaryFire.uasset
- Content/AI/Characters/BT/Boss/Enum_AttackType.uasset
- Content/AI/Characters/BT/Decorators/BTD_ShouldStun.uasset
- Content/AI/Characters/BT/EQS/EQS_BossBasicAttackRadius.uasset
- Content/AI/Characters/BT/EQS/EQS_Context_AttackTarget.uasset
- Content/AI/Characters/BT/Tasks/Tasks_Boss/BTT_ClearStun.uasset
- Content/AI/Characters/BT/Tasks/Tasks_Boss/BTT_IncreasePhase.uasset
- Content/AI/Characters/BT/Tasks/Tasks_Boss/BTT_PlayStun.uasset
- Content/AI/Characters/BT/Tasks/Tasks_Boss/BTT_PrimaryAttack.uasset
- Content/Levels/TestLevelBoss.umap
- 공격, Stun, Phase 조정 관련 BTT
- Boss 전용 TestLevel 설치
- 보스 기본 공격용 EQS
- Boss AttackType 판별용 enum
- Boss용 BT와 SubTree
- BP AI 수정
> [기능] Boss AI 관련 추가 사항

- Source/CH03Project/Private/DamageComponent.cpp
- TransDamage() 함수에서 데미지 report
> [기능] 기본 적 AI Damage 발생 시 Report

- Content/UITexture/BossHealthBar.uasset
- Content/UITexture/BossHpbar.uasset
- Content/UITexture/Item/Adrenaline.uasset
- Content/UITexture/Item/CardKey.uasset
- Content/UITexture/Item/Potion.uasset
- Content/UITexture/Item/Statue.uasset
- Content/Widget/WBP_HUDWidget.uasset
- Content/Widget/WBP_PauseMenu.uasset
- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/MenuWidget.cpp
- Source/CH03Project/Private/PauseWidget.cpp
- Source/CH03Project/Public/HUDWidget.h
- Source/CH03Project/Public/MenuWidget.h
- Source/CH03Project/Public/PauseWidget.h
1. 퀵슬롯 아이템 그림추가
2. Pause메뉴 추가(바인딩은 아직 미구현)
3. 게임엔드메뉴에 점수 바인딩
4. 히트마커 오류 수정
> [UI][수정] 퀵슬롯아이템, pause메뉴, 게임오버 메뉴.

- Content/AI/Characters/BP_AI_Boss.uasset
- Source/CH03Project/Private/BTT_ChargeAttack.cpp
- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Public/BaseStatComponent.h
- AddUniqueDynamic 및 Tag추가로 공격 여러번 불러지지 않도록 수정
-Stun 상태 돌입을 위해 Basecomponent에 체력 체크 내용 추가
> [기능] 보스 돌진 공격 오류 수정

- Config/DefaultEngine.ini
- Content/Levels/DoorTestLevel.umap
- Source/CH03Project/Private/Items/PickupItem.cpp
- Source/CH03Project/Private/MyCharacter.cpp
- Source/CH03Project/Public/MyCharacter.h
- DefaultEngine에 라인트레이스 채널 3번 추가
- PickupItem.cpp에서 Overlap으로 Interact 적용하던 함수 삭제
- MyCharacter에 E키 상호작용 함수 OnInteract 구현 및 바인딩 액션
> [기능] 아이템 E키로 줍는 기능 구현 완료

- Content/AI/Characters/BP_AI_Melee.uasset
- Content/AI/Characters/BP_AI_Ranged.uasset
- Content/DataTables/DropItemTable.uasset
- Source/CH03Project/Private/DropComponent.cpp
- Source/CH03Project/Private/DropItemTable.cpp
- Source/CH03Project/Public/DropComponent.h
- Source/CH03Project/Public/DropItemTable.h
- DropComponent로 죽였을 때 주변에 아이템 드롭
- DropItemTable로 보상 아이템 관리
> [기능] AI 죽였을 때 보상 드롭

- Content/Blueprints/BP_QuestTypeA.uasset
- Source/CH03Project/Private/GameModePlay.cpp
- Source/CH03Project/Private/GameStatePlay.cpp
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Private/MyPlayerController.cpp
- Source/CH03Project/Private/QuestObjectComponent.cpp
- Source/CH03Project/Private/QuestTypeA.cpp
- Source/CH03Project/Public/GameModePlay.h
- Source/CH03Project/Public/GameStatePlay.h
- Source/CH03Project/Public/QuestObjectComponent.h
- Source/CH03Project/Public/QuestTypeA.h
아이템에 따른 퀘스트 일부 변경
HUDWidget.cpp 미구현 함수 구현
> [리펙토링] 퀘스트 및 미구현 오류 수정

- Content/Character/BP_MyCharacter.uasset
- Source/CH03Project/Private/Items/BaseItem.cpp
- Source/CH03Project/Private/Items/InventoryComponent.cpp
- Source/CH03Project/Public/Items/BaseItem.h
- 수량이 0개일 때 아이템 사용이 불가능하도록 변경
- 델리게이트로 쿨타임 잔여시간 발행
- 인벤토리 컴포넌트 아이템 제거 삭제
> [기능, 수정] BaseItem 수정

- Content/Levels/MainMenuLevel.umap
- Content/Widget/Assets/Sound/MainMenu.uasset
- Content/Widget/Assets/Sound/MainMenuBGM.uasset
- Content/Widget/WBP_MainMenu.uasset
- MainMenu WBP에서 게임이름 수정
- MainMenu BGM 설정
> [기능] 메인메뉴 BGM과 게임제목 수정

- Content/AI/Characters/BP_AI_Melee.uasset
- Content/AI/Characters/BP_AI_Ranged.uasset
- Content/Items/BP_Pickup_AccBox.uasset
- Content/Items/ItemClass/BP_DropAcc.uasset
- Content/Items/ssssssss/Sci-fi_Container_Game.uasset
- Content/Items/ssssssss/Textures/Sci-fi_Container_Base_Color.uasset
- Content/Items/ssssssss/Textures/Sci-fi_Container_Emissive.uasset
- Content/Items/ssssssss/Textures/Sci-fi_Container_Metallic.uasset
- Content/Items/ssssssss/Textures/Sci-fi_Container_Mixed_AO.uasset
- Content/Items/ssssssss/Textures/Sci-fi_Container_Normal_OpenGL.uasset
- Content/Items/ssssssss/Textures/Sci-fi_Container_Roughness.uasset
- Content/Items/ssssssss/Textures/Sci-fi_Containerl_Normal_DirectX.uasset
- Content/Items/ssssssss/Материал.uasset
- Content/Weapon/BP_Rifle_1.uasset
- Source/CH03Project/Private/AccDropComponent.cpp
- Source/CH03Project/Private/BaseRangedWeapon.cpp
- Source/CH03Project/Private/BaseStatComponent.cpp
- Source/CH03Project/Private/DamageComponent.cpp
- Source/CH03Project/Private/PartEquipSlot.cpp
- Source/CH03Project/Private/WeaponAccCompoenent.cpp
- Source/CH03Project/Public/AccDropComponent.h
- Source/CH03Project/Public/BaseRangedWeapon.h
- Source/CH03Project/Public/DamageComponent.h
- Source/CH03Project/Public/GameStatePlay.h
- Source/CH03Project/Public/WeaponAccCompoenent.h
총기악세사리 아이템드랍 컴포넌트를 AI Enemy한테 부착하였습니다.
총기악세사리 부착효과 반영을 위해 레인지웨펀 일부 수정과 해당컴포넌트를 라이플에 부착하였습니다.
> [기능] 총기악세사리 아이템 드랍 및 부착효과반영

- Content/Inputs/IA_Inv.uasset
- Content/Widget_Inventory/WBP_GunAccessory.uasset
- Source/CH03Project/Private/MyPlayerController.cpp
1. i키를 누르면 ON, 꺼져있을땐  OFF 기능 추가
> [UI] 인벤토리 ON/OFF기능

- Content/Widget/Assets/Sound/HitSound.uasset
- Content/Widget/WBP_HUDWidget.uasset
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Public/HUDWidget.h
1. 적을 맞출때 마다 히트마커와 동시에 히트 사운드까지 추가
> [UI] 히트 사운드 추가

- Source/CH03Project/Private/AI/BTT_LasorAttack.cpp
- Source/CH03Project/Public/AI/BTT_LasorAttack.h
- DamageAmount에 deltaseconds 곱하는 부분 삭제
> [fix] Lasor 공격 안맞는 부분 수정

- Content/Widget/WBP_HUDWidget.uasset
> [UI] 퀵슬롯 번호 추가

- Config/DefaultEngine.ini
- Content/Asset/SciFi_BioLaboratory/NS_BrokenDoor.uasset
- Content/Levels/MainLevel.umap
- AI가 문에 가로막히는 부분 어색하지 않게 수정
- 네비 매시 Dynamic -> Static 으로 되돌림
> [레벨] 시작지점 복도구간 수정

- Content/Character/BP_MyCharacter.uasset
- Content/DataTables/ItemDataTable.uasset
- Content/Items/Sound/CatMeowSound.uasset
- Content/Items/Sound/DrinkAdrenaline.uasset
- Content/Items/Sound/DrinkPotion.uasset
- Source/CH03Project/Private/Items/Adrenaline.cpp
- Source/CH03Project/Private/Items/CatStatue.cpp
- Source/CH03Project/Private/Items/HealthPotion.cpp
- Source/CH03Project/Public/Items/ItemDataRow.h
- 체력포션, 아드레날린, 고양이 석상 사운드 추가
- 고양이 석상 단축키 3->4 로 변경
> [기능] 아이템 사용 사운드 추가, 고양이 석상 단축키 수정

- Content/AI/Characters/BT/Boss/BT_Enemy_Boss.uasset
- Content/AI/Characters/BT/Tasks/Tasks_Boss/BTT_ClearStun.uasset
- Content/AI/Characters/BT/Tasks/Tasks_Boss/BTT_IncreasePhase.uasset
- Content/Widget/Assets/Sound/BP_BGMManager.uasset
- Content/Widget/Assets/Sound/BP_BGMTrigger.uasset
- Content/Widget/Assets/Sound/BossBGM.uasset
- Content/Widget/Assets/Sound/MainLevelBasicBGM.uasset
- Source/CH03Project/Private/AI/BTS_AttackSelect.cpp
- Source/CH03Project/Private/AI/BTT_LRMAttack.cpp
- Source/CH03Project/Public/AI/BTS_AttackSelect.h
- BGM 사운드 에셋 추가
- 레벨에 배치할 사운드 매니저와 사운드 트리거 박스 구현
> [기능] 레벨 사운드 시스템

- Content/DataTables/DropItemTable.uasset
- Content/DataTables/DropItemTable_Boss.uasset
- Source/CH03Project/Private/DropComponent.cpp
- Source/CH03Project/Public/DropComponent.h
- 50% 확률로 0개가 무조건 나오도록 설정
- DropItemTable 조정
> [기능] AI 죽음 시 아이템 드롭 확률 조정

- Content/Levels/MainLevel.umap
- Source/CH03Project/Private/HUDWidget.cpp
- Source/CH03Project/Public/HUDWidget.h
> [개선] 타이머 클리어 추가

- Content/Items/BP_Pickup_AccBox.uasset
- Source/CH03Project/Private/DropComponent.cpp
> [리펙토링] 아이템 공중 드랍 수정
